apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: 'cloudtrader-identity'
spec:
  type: 0
  resourceID: '/subscriptions/< REDACTED >/resourcegroups/< REDACTED >/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cloudtrader-identity'
  clientID: '< REDACTED >'
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: azure-pod-identity-binding
spec:
  azureIdentity: 'cloudtrader-identity'
  selector: azure-pod-identity-binding-selector
