apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: 'true' # [OPTIONAL for Azure] if not provided, will default to "false"
    useVMManagedIdentity: 'false' # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    userAssignedIdentityID: '' # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: 'CloudTraderVault' # the name of the KeyVault
    cloudName: '' # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    cloudEnvFileName: '' # [OPTIONAL available for version > 0.0.7] use to define path to file for populating azure environment
    objects: |
      array:
        - |
          objectName: < REDACTED >
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: < REDACTED >
          objectType: secret
          objectVersion: ""
        - |
          objectName: < REDACTED >
          objectType: secret
          objectVersion: ""
    resourceGroup: 'resourceGroups/CloudTrader' # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: 'subscriptions/< REDACTED >' # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: '< REDACTED >' # the tenant ID of the KeyVault
  secretObjects:
    - secretName: < REDACTED >
      type: Opaque
      data:
        - objectName: < REDACTED >
          key: < REDACTED >
