apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtrader-traders
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: cloudtrader-traders
  template:
    metadata:
      labels:
        aadpodidbinding: azure-pod-identity-binding-selector
        app: cloudtrader-traders
    spec:
      containers:
        - image: 'cloudtrader.azurecr.io/cloudtrader-traders:be3b4c9eebec648c9af772ea4da03e37f4f18cf3'
          name: cloudtrader-traders
          ports:
            - containerPort: 80
