apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtrader-ui
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: cloudtrader-ui
  template:
    metadata:
      labels:
        app: cloudtrader-ui
    spec:
      containers:
        - env:
            - name: API_URL
              value: 'https://cloudtrader.ukwest.cloudapp.azure.com/api'
          image: 'cloudtrader.azurecr.io/cloudtrader-ui:v2'
          name: cloudtrader-ui
          ports:
            - containerPort: 80
