apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtrader-api
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: cloudtrader-api
  template:
    metadata:
      labels:
        aadpodidbinding: azure-pod-identity-binding-selector
        app: cloudtrader-api
    spec:
      containers:
        - env:
            - name: TRADERS_API_URL
              value: 'http://cloudtrader-traders'
            - name: MINES_API_URL
              value: 'http://cloudtrader-mines'
            - name: JwtTokenOptions__Key
              value: 'SomeTemporaryDummyKeyToBeChangedInFollowUpWork'
          image: 'cloudtrader.azurecr.io/cloudtrader-api:4d5f1238fb8b2fd9520e6b86d43c9af818a71360'
          name: cloudtrader-api
          ports:
            - containerPort: 80
