apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtrader-mines
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: cloudtrader-mines
  template:
    metadata:
      labels:
        aadpodidbinding: azure-pod-identity-binding-selector
        app: cloudtrader-mines
    spec:
      containers:
        - env:
            - name: API_URL
              value: 'https://cloudtrader.ukwest.cloudapp.azure.com/api'
          image: 'cloudtrader.azurecr.io/cloudtrader-mines:1b013884e629422ca57d1e456e57892c97eff96f'
          name: cloudtrader-mines
          ports:
            - containerPort: 80
